# Generated by Django 4.2 on 2024-07-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status_de",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pending"),
                    ("Completado", "Completed"),
                    ("Cancelado", "Cancelled"),
                    ("Enviado", "Shipped"),
                    ("Entregado", "Delivered"),
                ],
                default="Pendiente",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status_en",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pending"),
                    ("Completado", "Completed"),
                    ("Cancelado", "Cancelled"),
                    ("Enviado", "Shipped"),
                    ("Entregado", "Delivered"),
                ],
                default="Pendiente",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status_es",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pending"),
                    ("Completado", "Completed"),
                    ("Cancelado", "Cancelled"),
                    ("Enviado", "Shipped"),
                    ("Entregado", "Delivered"),
                ],
                default="Pendiente",
                max_length=10,
                null=True,
            ),
        ),
    ]
